=== tsmanishankar1/QatarLiving/QLN.Classified.MS/Data/Products.XSD
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="StoreFlyer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SubscriptionId" type="xs:string" minOccurs="0"/>
        <xs:element name="CompanyId" type="xs:string" minOccurs="0"/>
        <xs:element name="FlyerId" type="xs:string" minOccurs="0"/>
        <xs:element name="Products" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Product" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ProductName" type="xs:string"/>
                    <xs:element name="ProductLogo" type="xs:string"/>
                    <xs:element name="ProductPrice" type="xs:decimal"/>
                    <xs:element name="Currency" type="xs:string"/>
                    <xs:element name="ProductSummary" type="xs:string"/>
                    <xs:element name="ProductDescription" type="xs:string"/>
                    <xs:element name="PageNumber" type="xs:int"/>
                    <xs:element name="PageCoordinates" type="xs:string" minOccurs="0"/>
                    <xs:element name="Images" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ProductImage" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Features" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Feature" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tsmanishankar1/QatarLiving/QLN.Classified.MS/Data/Products-Incorrect.xml
<?xml version="1.0" encoding="utf-8"?>
<Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="products.xsd">

  <Product>
    <ProductLogo>smartphone-x10.png</ProductLogo>
    <ProductPrice>no price</ProductPrice>
    <Currency>USD</Currency>
    <ProductDetails>
      <ProductName>Smartphone X10</ProductName>
      <ProductSummary>Flagship smartphone with AI camera</ProductSummary>
      <ProductDescription>High-resolution OLED screen, 128GB storage, 5G support</ProductDescription>
      <Images>
        <ProductImage>front.jpg</ProductImage>
        <ProductImage>back.jpg</ProductImage>
      </Images>
      <Features>
        <Feature>Waterproof</Feature>
        <Feature>Face Recognition</Feature>
        <Feature>Fast Charging</Feature>
      </Features>
    </ProductDetails>
  </Product>

</Products>

=== tsmanishankar1/QatarLiving/QLN.Classified.MS/Data/Products.xml
<?xml version="1.0" encoding="utf-8"?>
<Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="products.xsd">

	<Product>
		<ProductName>Smartphone X10</ProductName>
		<ProductLogo>https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/IPhone_X_vector.svg/512px-IPhone_X_vector.svg.png</ProductLogo>
		<ProductPrice>699.99</ProductPrice>
		<Currency>USD</Currency>
		<ProductDetails>
			<ProductName>Smartphone X10</ProductName>
			<ProductSummary>Flagship smartphone with AI camera</ProductSummary>
			<ProductDescription>High-resolution OLED screen, 128GB storage, 5G support</ProductDescription>
			<Images>
				<ProductImage>https://images.unsplash.com/photo-1511707171634-5f897ff02aa9</ProductImage>
				<ProductImage>https://images.unsplash.com/photo-1510552776732-03e61cf4b144</ProductImage>
			</Images>
			<Features>
				<Feature>Waterproof</Feature>
				<Feature>Face Recognition</Feature>
				<Feature>Fast Charging</Feature>
			</Features>
		</ProductDetails>
	</Product>


</Products>
